name: Deployment...
on:
  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: muhammadqodirmuminov/app:${{github.sha}}
      - name: Deploy To server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_HOST}}
          username: ${{secrets.SERVER_USERNAME}}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            sudo docker stop app || true
            sudo docker rm app || true
            sudo docker pull ${{secrets.DOCKER_USERNAME}}/app:${{github.sha}}
            sudo docker run --name app -d -p 8080:5173 ${{secrets.DOCKER_USERNAME}}/app:${{github.sha}}
            
