name: ci
on:
  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: muhammadqodirmuminov/app:${{github.sha}}
      - name: Deploy To server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_HOST}}
          username: ${{secrets.SERVER_USERNAME}}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            sudo apt-get update -y
            sudo apt-get install -y sshpass
            sshpass -p ${{ secrets.SSH_PASSWORD }}
            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 
            docker stop app  || true && docker rm app || true
            "docker pull muhammadqodirmuminov/app:${{ github.sha }} && docker run -d -p 5173:5173 --name app muhammadqodirmuminov/app:${{ github.sha }}"
            
