name: deployment
on: 
  push:
    branches:
      - main
      - dev
      - 'dev-*'
      - 'feat/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test app
        uses: actions/checkout@v3
      - name: Install dependancies
        run: npm ci
      - name: Test
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name : Install deps
        run: npm ci
      - name: Build app
        run: npm run build
      - name: Publish js filename
        id: publish
        run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying..."
      - name: GET filename
        run: echo "${{ needs.build.outputs.script-file }}"
      - name: Download artifact
        uses: actions/download-artifact@v3
        with: 
          name: dist-files