name: deployment
on: 
  pull_request:
    types:
      - opened
    branches:
      - main
      - 'dev-*'
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
      - 'dev-*'
      - 'feat/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: get-code
        uses: actions/checkout@v3
      - name: install deps
        run: npm ci			
      - name: Link
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."